# Generated by Django 3.0.5 on 2020-04-27 02:02

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200425_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='current',
        ),
        migrations.AlterField(
            model_name='exercisetype',
            name='muscles_worked',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Abs', 'Abs'), ('Back', 'Back'), ('Biceps', 'Biceps'), ('Calves', 'Calves'), ('Chest', 'Chest'), ('Forearms', 'Forearms'), ('Glutes', 'Glutes'), ('Hamstrings', 'Hamstrings'), ('Quadriceps', 'Quadriceps'), ('Shoulders', 'Shoulders'), ('Traps', 'Traps'), ('Triceps', 'Triceps'), ('Upper Back', 'Upper Back'), ('Lower Back', 'Lower Back')], default='biceps', max_length=120),
        ),
        migrations.AlterField(
            model_name='exercisetype',
            name='name',
            field=models.CharField(choices=[('Bicep-Curls', 'Bicep Curls'), ('Squats', 'Squats'), ('Jumping-Jacks', 'Jumping Jacks'), ('Bench-Press', 'Bench Press'), ('Bulgarian-Split-Squat', 'Bulgarian Split Squat'), ('Chest-Fly', 'Chest Fly'), ('Crunches', 'Crunches'), ('Curtsy-Lunge', 'Curtsy Lunge'), ('Good-Morning', 'Good Morning'), ('Hip-Abduction', 'Hip Abduction'), ('Hip-Thrusts', 'Hip Thrusts'), ('Leg-Extension', 'Leg Extension'), ('Leg-Press', 'Leg Press'), ('Lying-Leg-Curl', 'Lying Leg Curl'), ('RDL', 'RDL'), ('Russian-Twists', 'Russian Twists'), ('Sumo-Deadlift', 'Sumo Deadlift'), ('Tricep-Extension', 'Tricep Extension')], default='bicep-curls', max_length=120),
        ),
        migrations.AlterField(
            model_name='workout',
            name='avg_time_completed',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='total_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
