# Generated by Django 3.0.5 on 2020-04-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200427_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='weight_lifted',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
