# Generated by Django 3.0.5 on 2020-04-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_workout_weight_lifted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='weight_lifted',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
